### ISSUE TITLE
PHPStorm compability 

### ISSUE THREAD

**Issue by grempa** [misterboe/typo3-live-templates#2]
Please make it compatible for just released PhpStorm 2023.3

**Comment by misterboe** [comment]
JetBrains is reviewing this update. Please expect it to be approved within two business days of the upload.

**Comment by misterboe** [comment]
I have some issues with the update. Still trying to fix it.

**Comment by misterboe** [comment]
switched to new repo:
https://github.com/misterboe/typo3-intellij-livetemplates
